codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        branches:
          - main

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true
