name: Publish Docs to Wiki

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest   # Linux is fine now

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore & build (with XML docs)
      run: dotnet build Shoegaze.LastFM.sln --configuration Release

    - name: Install xmldocmd
      run: dotnet tool install -g xmldocmd

    - name: Generate Markdown Docs
      run: |
        mkdir md-docs
        xmldocmd ./src/Shoegaze.LastFM/bin/Release/net9.0/Shoegaze.LastFM.dll md-docs --newline lf

    - name: Checkout Wiki
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy Generated Markdown to Wiki
      run: |
        rm -rf wiki/*
        cp -r md-docs/* wiki/

    - name: Commit & Push to Wiki
      run: |
        cd wiki
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update docs from ${{ github.sha }}" || echo "No changes to commit"
        git push